//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.15 at 12:54:41 PM MST 
//


package com.orderwire.cxml.dll;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element ref="{}DeductionAmount"/&gt;
 *         &lt;element ref="{}DeductionPercent"/&gt;
 *         &lt;element ref="{}DeductedPrice"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deductionAmount",
    "deductionPercent",
    "deductedPrice"
})
@XmlRootElement(name = "AdditionalDeduction")
public class AdditionalDeduction {

    @XmlElement(name = "DeductionAmount")
    protected DeductionAmount deductionAmount;
    @XmlElement(name = "DeductionPercent")
    protected DeductionPercent deductionPercent;
    @XmlElement(name = "DeductedPrice")
    protected DeductedPrice deductedPrice;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the deductionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link DeductionAmount }
     *     
     */
    public DeductionAmount getDeductionAmount() {
        return deductionAmount;
    }

    /**
     * Sets the value of the deductionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeductionAmount }
     *     
     */
    public void setDeductionAmount(DeductionAmount value) {
        this.deductionAmount = value;
    }

    /**
     * Gets the value of the deductionPercent property.
     * 
     * @return
     *     possible object is
     *     {@link DeductionPercent }
     *     
     */
    public DeductionPercent getDeductionPercent() {
        return deductionPercent;
    }

    /**
     * Sets the value of the deductionPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeductionPercent }
     *     
     */
    public void setDeductionPercent(DeductionPercent value) {
        this.deductionPercent = value;
    }

    /**
     * Gets the value of the deductedPrice property.
     * 
     * @return
     *     possible object is
     *     {@link DeductedPrice }
     *     
     */
    public DeductedPrice getDeductedPrice() {
        return deductedPrice;
    }

    /**
     * Sets the value of the deductedPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeductedPrice }
     *     
     */
    public void setDeductedPrice(DeductedPrice value) {
        this.deductedPrice = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
