//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.15 at 12:54:41 PM MST 
//


package com.orderwire.cxml.dll;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}OCInstruction" minOccurs="0"/&gt;
 *         &lt;element ref="{}ASNInstruction" minOccurs="0"/&gt;
 *         &lt;element ref="{}InvoiceInstruction" minOccurs="0"/&gt;
 *         &lt;element ref="{}SESInstruction" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ocInstruction",
    "asnInstruction",
    "invoiceInstruction",
    "sesInstruction"
})
@XmlRootElement(name = "ControlKeys")
public class ControlKeys {

    @XmlElement(name = "OCInstruction")
    protected OCInstruction ocInstruction;
    @XmlElement(name = "ASNInstruction")
    protected ASNInstruction asnInstruction;
    @XmlElement(name = "InvoiceInstruction")
    protected InvoiceInstruction invoiceInstruction;
    @XmlElement(name = "SESInstruction")
    protected SESInstruction sesInstruction;

    /**
     * Gets the value of the ocInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link OCInstruction }
     *     
     */
    public OCInstruction getOCInstruction() {
        return ocInstruction;
    }

    /**
     * Sets the value of the ocInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link OCInstruction }
     *     
     */
    public void setOCInstruction(OCInstruction value) {
        this.ocInstruction = value;
    }

    /**
     * Gets the value of the asnInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link ASNInstruction }
     *     
     */
    public ASNInstruction getASNInstruction() {
        return asnInstruction;
    }

    /**
     * Sets the value of the asnInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASNInstruction }
     *     
     */
    public void setASNInstruction(ASNInstruction value) {
        this.asnInstruction = value;
    }

    /**
     * Gets the value of the invoiceInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceInstruction }
     *     
     */
    public InvoiceInstruction getInvoiceInstruction() {
        return invoiceInstruction;
    }

    /**
     * Sets the value of the invoiceInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceInstruction }
     *     
     */
    public void setInvoiceInstruction(InvoiceInstruction value) {
        this.invoiceInstruction = value;
    }

    /**
     * Gets the value of the sesInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link SESInstruction }
     *     
     */
    public SESInstruction getSESInstruction() {
        return sesInstruction;
    }

    /**
     * Sets the value of the sesInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link SESInstruction }
     *     
     */
    public void setSESInstruction(SESInstruction value) {
        this.sesInstruction = value;
    }

}
