//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.15 at 12:54:41 PM MST 
//


package com.orderwire.cxml.dll;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}EANID" minOccurs="0"/&gt;
 *         &lt;element ref="{}EuropeanWasteCatalogID" minOccurs="0"/&gt;
 *         &lt;element ref="{}Characteristic" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eanid",
    "europeanWasteCatalogID",
    "characteristic"
})
@XmlRootElement(name = "ItemDetailRetail")
public class ItemDetailRetail {

    @XmlElement(name = "EANID")
    protected String eanid;
    @XmlElement(name = "EuropeanWasteCatalogID")
    protected String europeanWasteCatalogID;
    @XmlElement(name = "Characteristic")
    protected List<Characteristic> characteristic;

    /**
     * Gets the value of the eanid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEANID() {
        return eanid;
    }

    /**
     * Sets the value of the eanid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEANID(String value) {
        this.eanid = value;
    }

    /**
     * Gets the value of the europeanWasteCatalogID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEuropeanWasteCatalogID() {
        return europeanWasteCatalogID;
    }

    /**
     * Sets the value of the europeanWasteCatalogID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEuropeanWasteCatalogID(String value) {
        this.europeanWasteCatalogID = value;
    }

    /**
     * Gets the value of the characteristic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the characteristic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacteristic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Characteristic }
     * 
     * 
     */
    public List<Characteristic> getCharacteristic() {
        if (characteristic == null) {
            characteristic = new ArrayList<Characteristic>();
        }
        return this.characteristic;
    }

}
