//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.15 at 12:54:41 PM MST 
//


package com.orderwire.cxml.dll;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ItemDetailRetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="isConfigurableMaterial"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemDetailRetail"
})
@XmlRootElement(name = "ItemDetailIndustry")
public class ItemDetailIndustry {

    @XmlElement(name = "ItemDetailRetail")
    protected ItemDetailRetail itemDetailRetail;
    @XmlAttribute(name = "isConfigurableMaterial")
    protected String isConfigurableMaterial;

    /**
     * Gets the value of the itemDetailRetail property.
     * 
     * @return
     *     possible object is
     *     {@link ItemDetailRetail }
     *     
     */
    public ItemDetailRetail getItemDetailRetail() {
        return itemDetailRetail;
    }

    /**
     * Sets the value of the itemDetailRetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemDetailRetail }
     *     
     */
    public void setItemDetailRetail(ItemDetailRetail value) {
        this.itemDetailRetail = value;
    }

    /**
     * Gets the value of the isConfigurableMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsConfigurableMaterial() {
        return isConfigurableMaterial;
    }

    /**
     * Sets the value of the isConfigurableMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsConfigurableMaterial(String value) {
        this.isConfigurableMaterial = value;
    }

}
