//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.15 at 12:54:41 PM MST 
//


package com.orderwire.cxml.dll;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}OriginalPrice" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{}AdditionalDeduction"/&gt;
 *           &lt;element ref="{}AdditionalCost"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}Tax" minOccurs="0"/&gt;
 *         &lt;element ref="{}ModificationDetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "originalPrice",
    "additionalDeduction",
    "additionalCost",
    "tax",
    "modificationDetail"
})
@XmlRootElement(name = "Modification")
public class Modification {

    @XmlElement(name = "OriginalPrice")
    protected OriginalPrice originalPrice;
    @XmlElement(name = "AdditionalDeduction")
    protected AdditionalDeduction additionalDeduction;
    @XmlElement(name = "AdditionalCost")
    protected AdditionalCost additionalCost;
    @XmlElement(name = "Tax")
    protected Tax tax;
    @XmlElement(name = "ModificationDetail")
    protected ModificationDetail modificationDetail;
    @XmlAttribute(name = "level")
    protected String level;

    /**
     * Gets the value of the originalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalPrice }
     *     
     */
    public OriginalPrice getOriginalPrice() {
        return originalPrice;
    }

    /**
     * Sets the value of the originalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalPrice }
     *     
     */
    public void setOriginalPrice(OriginalPrice value) {
        this.originalPrice = value;
    }

    /**
     * Gets the value of the additionalDeduction property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalDeduction }
     *     
     */
    public AdditionalDeduction getAdditionalDeduction() {
        return additionalDeduction;
    }

    /**
     * Sets the value of the additionalDeduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalDeduction }
     *     
     */
    public void setAdditionalDeduction(AdditionalDeduction value) {
        this.additionalDeduction = value;
    }

    /**
     * Gets the value of the additionalCost property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalCost }
     *     
     */
    public AdditionalCost getAdditionalCost() {
        return additionalCost;
    }

    /**
     * Sets the value of the additionalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalCost }
     *     
     */
    public void setAdditionalCost(AdditionalCost value) {
        this.additionalCost = value;
    }

    /**
     * Gets the value of the tax property.
     * 
     * @return
     *     possible object is
     *     {@link Tax }
     *     
     */
    public Tax getTax() {
        return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tax }
     *     
     */
    public void setTax(Tax value) {
        this.tax = value;
    }

    /**
     * Gets the value of the modificationDetail property.
     * 
     * @return
     *     possible object is
     *     {@link ModificationDetail }
     *     
     */
    public ModificationDetail getModificationDetail() {
        return modificationDetail;
    }

    /**
     * Sets the value of the modificationDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationDetail }
     *     
     */
    public void setModificationDetail(ModificationDetail value) {
        this.modificationDetail = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

}
