//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.15 at 12:54:41 PM MST 
//


package com.orderwire.cxml.dll;

import java.math.BigInteger;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.orderwire.cxml.dll package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Identity_QNAME = new QName("", "Identity");
    private final static QName _SharedSecret_QNAME = new QName("", "SharedSecret");
    private final static QName _UserAgent_QNAME = new QName("", "UserAgent");
    private final static QName _ShortName_QNAME = new QName("", "ShortName");
    private final static QName _TaxRegime_QNAME = new QName("", "TaxRegime");
    private final static QName _DeliverTo_QNAME = new QName("", "DeliverTo");
    private final static QName _Street_QNAME = new QName("", "Street");
    private final static QName _City_QNAME = new QName("", "City");
    private final static QName _State_QNAME = new QName("", "State");
    private final static QName _PostalCode_QNAME = new QName("", "PostalCode");
    private final static QName _AreaOrCityCode_QNAME = new QName("", "AreaOrCityCode");
    private final static QName _Number_QNAME = new QName("", "Number");
    private final static QName _Extension_QNAME = new QName("", "Extension");
    private final static QName _ShippingContractNumber_QNAME = new QName("", "ShippingContractNumber");
    private final static QName _SupplierPartID_QNAME = new QName("", "SupplierPartID");
    private final static QName _SupplierPartAuxiliaryID_QNAME = new QName("", "SupplierPartAuxiliaryID");
    private final static QName _BuyerPartID_QNAME = new QName("", "BuyerPartID");
    private final static QName _UnitOfMeasure_QNAME = new QName("", "UnitOfMeasure");
    private final static QName _ManufacturerPartID_QNAME = new QName("", "ManufacturerPartID");
    private final static QName _LeadTime_QNAME = new QName("", "LeadTime");
    private final static QName _EANID_QNAME = new QName("", "EANID");
    private final static QName _EuropeanWasteCatalogID_QNAME = new QName("", "EuropeanWasteCatalogID");
    private final static QName _PlannedAcceptanceDays_QNAME = new QName("", "PlannedAcceptanceDays");
    private final static QName _MaxQuantity_QNAME = new QName("", "MaxQuantity");
    private final static QName _MinQuantity_QNAME = new QName("", "MinQuantity");
    private final static QName _OrderProtocol_QNAME = new QName("", "OrderProtocol");
    private final static QName _ComponentID_QNAME = new QName("", "ComponentID");
    private final static QName _ProductRevisionID_QNAME = new QName("", "ProductRevisionID");
    private final static QName _BuyerBatchID_QNAME = new QName("", "BuyerBatchID");
    private final static QName _SupplierBatchID_QNAME = new QName("", "SupplierBatchID");
    private final static QName _ParentID_QNAME = new QName("", "ParentID");
    private final static QName _PromotionVariantID_QNAME = new QName("", "PromotionVariantID");
    private final static QName _PromotionDealID_QNAME = new QName("", "PromotionDealID");
    private final static QName _SerialNumber_QNAME = new QName("", "SerialNumber");
    private final static QName _PackagingLevelCode_QNAME = new QName("", "PackagingLevelCode");
    private final static QName _PackageTypeCodeIdentifierCode_QNAME = new QName("", "PackageTypeCodeIdentifierCode");
    private final static QName _ShippingContainerSerialCode_QNAME = new QName("", "ShippingContainerSerialCode");
    private final static QName _ShippingContainerSerialCodeReference_QNAME = new QName("", "ShippingContainerSerialCodeReference");
    private final static QName _GlobalIndividualAssetID_QNAME = new QName("", "GlobalIndividualAssetID");
    private final static QName _ReturnablePackageID_QNAME = new QName("", "ReturnablePackageID");
    private final static QName _PackageTrackingID_QNAME = new QName("", "PackageTrackingID");
    private final static QName _ShippingMark_QNAME = new QName("", "ShippingMark");
    private final static QName _QuantityVarianceNote_QNAME = new QName("", "QuantityVarianceNote");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.orderwire.cxml.dll
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CXML }
     * 
     */
    public CXML createCXML() {
        return new CXML();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link From }
     * 
     */
    public From createFrom() {
        return new From();
    }

    /**
     * Create an instance of {@link Credential }
     * 
     */
    public Credential createCredential() {
        return new Credential();
    }

    /**
     * Create an instance of {@link DigitalSignature }
     * 
     */
    public DigitalSignature createDigitalSignature() {
        return new DigitalSignature();
    }

    /**
     * Create an instance of {@link CredentialMac }
     * 
     */
    public CredentialMac createCredentialMac() {
        return new CredentialMac();
    }

    /**
     * Create an instance of {@link To }
     * 
     */
    public To createTo() {
        return new To();
    }

    /**
     * Create an instance of {@link Sender }
     * 
     */
    public Sender createSender() {
        return new Sender();
    }

    /**
     * Create an instance of {@link Path }
     * 
     */
    public Path createPath() {
        return new Path();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link OriginalDocument }
     * 
     */
    public OriginalDocument createOriginalDocument() {
        return new OriginalDocument();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link OrderRequest }
     * 
     */
    public OrderRequest createOrderRequest() {
        return new OrderRequest();
    }

    /**
     * Create an instance of {@link OrderRequestHeader }
     * 
     */
    public OrderRequestHeader createOrderRequestHeader() {
        return new OrderRequestHeader();
    }

    /**
     * Create an instance of {@link Total }
     * 
     */
    public Total createTotal() {
        return new Total();
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link Modifications }
     * 
     */
    public Modifications createModifications() {
        return new Modifications();
    }

    /**
     * Create an instance of {@link Modification }
     * 
     */
    public Modification createModification() {
        return new Modification();
    }

    /**
     * Create an instance of {@link OriginalPrice }
     * 
     */
    public OriginalPrice createOriginalPrice() {
        return new OriginalPrice();
    }

    /**
     * Create an instance of {@link AdditionalDeduction }
     * 
     */
    public AdditionalDeduction createAdditionalDeduction() {
        return new AdditionalDeduction();
    }

    /**
     * Create an instance of {@link DeductionAmount }
     * 
     */
    public DeductionAmount createDeductionAmount() {
        return new DeductionAmount();
    }

    /**
     * Create an instance of {@link DeductionPercent }
     * 
     */
    public DeductionPercent createDeductionPercent() {
        return new DeductionPercent();
    }

    /**
     * Create an instance of {@link DeductedPrice }
     * 
     */
    public DeductedPrice createDeductedPrice() {
        return new DeductedPrice();
    }

    /**
     * Create an instance of {@link AdditionalCost }
     * 
     */
    public AdditionalCost createAdditionalCost() {
        return new AdditionalCost();
    }

    /**
     * Create an instance of {@link Percentage }
     * 
     */
    public Percentage createPercentage() {
        return new Percentage();
    }

    /**
     * Create an instance of {@link Tax }
     * 
     */
    public Tax createTax() {
        return new Tax();
    }

    /**
     * Create an instance of {@link TaxAdjustmentAmount }
     * 
     */
    public TaxAdjustmentAmount createTaxAdjustmentAmount() {
        return new TaxAdjustmentAmount();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link TaxDetail }
     * 
     */
    public TaxDetail createTaxDetail() {
        return new TaxDetail();
    }

    /**
     * Create an instance of {@link TaxableAmount }
     * 
     */
    public TaxableAmount createTaxableAmount() {
        return new TaxableAmount();
    }

    /**
     * Create an instance of {@link TaxAmount }
     * 
     */
    public TaxAmount createTaxAmount() {
        return new TaxAmount();
    }

    /**
     * Create an instance of {@link TaxLocation }
     * 
     */
    public TaxLocation createTaxLocation() {
        return new TaxLocation();
    }

    /**
     * Create an instance of {@link TriangularTransactionLawReference }
     * 
     */
    public TriangularTransactionLawReference createTriangularTransactionLawReference() {
        return new TriangularTransactionLawReference();
    }

    /**
     * Create an instance of {@link TaxExemption }
     * 
     */
    public TaxExemption createTaxExemption() {
        return new TaxExemption();
    }

    /**
     * Create an instance of {@link ExemptReason }
     * 
     */
    public ExemptReason createExemptReason() {
        return new ExemptReason();
    }

    /**
     * Create an instance of {@link Extrinsic }
     * 
     */
    public Extrinsic createExtrinsic() {
        return new Extrinsic();
    }

    /**
     * Create an instance of {@link Distribution }
     * 
     */
    public Distribution createDistribution() {
        return new Distribution();
    }

    /**
     * Create an instance of {@link Accounting }
     * 
     */
    public Accounting createAccounting() {
        return new Accounting();
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link AccountingSegment }
     * 
     */
    public AccountingSegment createAccountingSegment() {
        return new AccountingSegment();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Charge }
     * 
     */
    public Charge createCharge() {
        return new Charge();
    }

    /**
     * Create an instance of {@link ModificationDetail }
     * 
     */
    public ModificationDetail createModificationDetail() {
        return new ModificationDetail();
    }

    /**
     * Create an instance of {@link ShipTo }
     * 
     */
    public ShipTo createShipTo() {
        return new ShipTo();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link PostalAddressPre }
     * 
     */
    public PostalAddressPre createPostalAddress() {
        return new PostalAddressPre();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link CarrierIdentifier }
     * 
     */
    public CarrierIdentifier createCarrierIdentifier() {
        return new CarrierIdentifier();
    }

    /**
     * Create an instance of {@link TransportInformation }
     * 
     */
    public TransportInformation createTransportInformation() {
        return new TransportInformation();
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link TelephoneNumber }
     * 
     */
    public TelephoneNumber createTelephoneNumber() {
        return new TelephoneNumber();
    }

    /**
     * Create an instance of {@link CountryCode }
     * 
     */
    public CountryCode createCountryCode() {
        return new CountryCode();
    }

    /**
     * Create an instance of {@link Fax }
     * 
     */
    public Fax createFax() {
        return new Fax();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link IdReference }
     * 
     */
    public IdReference createIdReference() {
        return new IdReference();
    }

    /**
     * Create an instance of {@link Creator }
     * 
     */
    public Creator createCreator() {
        return new Creator();
    }

    /**
     * Create an instance of {@link ShippingInstructions }
     * 
     */
    public ShippingInstructions createShippingInstructions() {
        return new ShippingInstructions();
    }

    /**
     * Create an instance of {@link BillTo }
     * 
     */
    public BillTo createBillTo() {
        return new BillTo();
    }

    /**
     * Create an instance of {@link LegalEntity }
     * 
     */
    public LegalEntity createLegalEntity() {
        return new LegalEntity();
    }

    /**
     * Create an instance of {@link OrganizationalUnit }
     * 
     */
    public OrganizationalUnit createOrganizationalUnit() {
        return new OrganizationalUnit();
    }

    /**
     * Create an instance of {@link Shipping }
     * 
     */
    public Shipping createShipping() {
        return new Shipping();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link PCard }
     * 
     */
    public PCard createPCard() {
        return new PCard();
    }

    /**
     * Create an instance of {@link PaymentTerm }
     * 
     */
    public PaymentTerm createPaymentTerm() {
        return new PaymentTerm();
    }

    /**
     * Create an instance of {@link Discount }
     * 
     */
    public Discount createDiscount() {
        return new Discount();
    }

    /**
     * Create an instance of {@link DiscountPercent }
     * 
     */
    public DiscountPercent createDiscountPercent() {
        return new DiscountPercent();
    }

    /**
     * Create an instance of {@link DiscountAmount }
     * 
     */
    public DiscountAmount createDiscountAmount() {
        return new DiscountAmount();
    }

    /**
     * Create an instance of {@link Comments }
     * 
     */
    public Comments createComments() {
        return new Comments();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link Followup }
     * 
     */
    public Followup createFollowup() {
        return new Followup();
    }

    /**
     * Create an instance of {@link ControlKeys }
     * 
     */
    public ControlKeys createControlKeys() {
        return new ControlKeys();
    }

    /**
     * Create an instance of {@link OCInstruction }
     * 
     */
    public OCInstruction createOCInstruction() {
        return new OCInstruction();
    }

    /**
     * Create an instance of {@link Lower }
     * 
     */
    public Lower createLower() {
        return new Lower();
    }

    /**
     * Create an instance of {@link Tolerances }
     * 
     */
    public Tolerances createTolerances() {
        return new Tolerances();
    }

    /**
     * Create an instance of {@link QuantityTolerance }
     * 
     */
    public QuantityTolerance createQuantityTolerance() {
        return new QuantityTolerance();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link PriceTolerance }
     * 
     */
    public PriceTolerance createPriceTolerance() {
        return new PriceTolerance();
    }

    /**
     * Create an instance of {@link TimeTolerance }
     * 
     */
    public TimeTolerance createTimeTolerance() {
        return new TimeTolerance();
    }

    /**
     * Create an instance of {@link Upper }
     * 
     */
    public Upper createUpper() {
        return new Upper();
    }

    /**
     * Create an instance of {@link ASNInstruction }
     * 
     */
    public ASNInstruction createASNInstruction() {
        return new ASNInstruction();
    }

    /**
     * Create an instance of {@link InvoiceInstruction }
     * 
     */
    public InvoiceInstruction createInvoiceInstruction() {
        return new InvoiceInstruction();
    }

    /**
     * Create an instance of {@link TemporaryPrice }
     * 
     */
    public TemporaryPrice createTemporaryPrice() {
        return new TemporaryPrice();
    }

    /**
     * Create an instance of {@link SESInstruction }
     * 
     */
    public SESInstruction createSESInstruction() {
        return new SESInstruction();
    }

    /**
     * Create an instance of {@link DocumentReference }
     * 
     */
    public DocumentReference createDocumentReference() {
        return new DocumentReference();
    }

    /**
     * Create an instance of {@link SupplierOrderInfo }
     * 
     */
    public SupplierOrderInfo createSupplierOrderInfo() {
        return new SupplierOrderInfo();
    }

    /**
     * Create an instance of {@link TermsOfDelivery }
     * 
     */
    public TermsOfDelivery createTermsOfDelivery() {
        return new TermsOfDelivery();
    }

    /**
     * Create an instance of {@link TermsOfDeliveryCode }
     * 
     */
    public TermsOfDeliveryCode createTermsOfDeliveryCode() {
        return new TermsOfDeliveryCode();
    }

    /**
     * Create an instance of {@link ShippingPaymentMethod }
     * 
     */
    public ShippingPaymentMethod createShippingPaymentMethod() {
        return new ShippingPaymentMethod();
    }

    /**
     * Create an instance of {@link TransportTerms }
     * 
     */
    public TransportTerms createTransportTerms() {
        return new TransportTerms();
    }

    /**
     * Create an instance of {@link DeliveryPeriod }
     * 
     */
    public DeliveryPeriod createDeliveryPeriod() {
        return new DeliveryPeriod();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link OrderRequestHeaderIndustry }
     * 
     */
    public OrderRequestHeaderIndustry createOrderRequestHeaderIndustry() {
        return new OrderRequestHeaderIndustry();
    }

    /**
     * Create an instance of {@link ReferenceDocumentInfo }
     * 
     */
    public ReferenceDocumentInfo createReferenceDocumentInfo() {
        return new ReferenceDocumentInfo();
    }

    /**
     * Create an instance of {@link DocumentInfo }
     * 
     */
    public DocumentInfo createDocumentInfo() {
        return new DocumentInfo();
    }

    /**
     * Create an instance of {@link DateInfo }
     * 
     */
    public DateInfo createDateInfo() {
        return new DateInfo();
    }

    /**
     * Create an instance of {@link Priority }
     * 
     */
    public Priority createPriority() {
        return new Priority();
    }

    /**
     * Create an instance of {@link ExternalDocumentType }
     * 
     */
    public ExternalDocumentType createExternalDocumentType() {
        return new ExternalDocumentType();
    }

    /**
     * Create an instance of {@link QualityInfo }
     * 
     */
    public QualityInfo createQualityInfo() {
        return new QualityInfo();
    }

    /**
     * Create an instance of {@link CertificateInfo }
     * 
     */
    public CertificateInfo createCertificateInfo() {
        return new CertificateInfo();
    }

    /**
     * Create an instance of {@link AssetInfo }
     * 
     */
    public AssetInfo createAssetInfo() {
        return new AssetInfo();
    }

    /**
     * Create an instance of {@link ItemOut }
     * 
     */
    public ItemOut createItemOut() {
        return new ItemOut();
    }

    /**
     * Create an instance of {@link ItemID }
     * 
     */
    public ItemID createItemID() {
        return new ItemID();
    }

    /**
     * Create an instance of {@link ItemDetail }
     * 
     */
    public ItemDetail createItemDetail() {
        return new ItemDetail();
    }

    /**
     * Create an instance of {@link UnitPrice }
     * 
     */
    public UnitPrice createUnitPrice() {
        return new UnitPrice();
    }

    /**
     * Create an instance of {@link OverallLimit }
     * 
     */
    public OverallLimit createOverallLimit() {
        return new OverallLimit();
    }

    /**
     * Create an instance of {@link ExpectedLimit }
     * 
     */
    public ExpectedLimit createExpectedLimit() {
        return new ExpectedLimit();
    }

    /**
     * Create an instance of {@link PriceBasisQuantity }
     * 
     */
    public PriceBasisQuantity createPriceBasisQuantity() {
        return new PriceBasisQuantity();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link ManufacturerName }
     * 
     */
    public ManufacturerName createManufacturerName() {
        return new ManufacturerName();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link ItemDetailIndustry }
     * 
     */
    public ItemDetailIndustry createItemDetailIndustry() {
        return new ItemDetailIndustry();
    }

    /**
     * Create an instance of {@link ItemDetailRetail }
     * 
     */
    public ItemDetailRetail createItemDetailRetail() {
        return new ItemDetailRetail();
    }

    /**
     * Create an instance of {@link Characteristic }
     * 
     */
    public Characteristic createCharacteristic() {
        return new Characteristic();
    }

    /**
     * Create an instance of {@link AttachmentReference }
     * 
     */
    public AttachmentReference createAttachmentReference() {
        return new AttachmentReference();
    }

    /**
     * Create an instance of {@link InternalID }
     * 
     */
    public InternalID createInternalID() {
        return new InternalID();
    }

    /**
     * Create an instance of {@link BlanketItemDetail }
     * 
     */
    public BlanketItemDetail createBlanketItemDetail() {
        return new BlanketItemDetail();
    }

    /**
     * Create an instance of {@link MaxAmount }
     * 
     */
    public MaxAmount createMaxAmount() {
        return new MaxAmount();
    }

    /**
     * Create an instance of {@link MinAmount }
     * 
     */
    public MinAmount createMinAmount() {
        return new MinAmount();
    }

    /**
     * Create an instance of {@link MaxContractAmount }
     * 
     */
    public MaxContractAmount createMaxContractAmount() {
        return new MaxContractAmount();
    }

    /**
     * Create an instance of {@link MaxAdhocAmount }
     * 
     */
    public MaxAdhocAmount createMaxAdhocAmount() {
        return new MaxAdhocAmount();
    }

    /**
     * Create an instance of {@link SupplierID }
     * 
     */
    public SupplierID createSupplierID() {
        return new SupplierID();
    }

    /**
     * Create an instance of {@link SupplierList }
     * 
     */
    public SupplierList createSupplierList() {
        return new SupplierList();
    }

    /**
     * Create an instance of {@link Supplier }
     * 
     */
    public Supplier createSupplier() {
        return new Supplier();
    }

    /**
     * Create an instance of {@link SupplierLocation }
     * 
     */
    public SupplierLocation createSupplierLocation() {
        return new SupplierLocation();
    }

    /**
     * Create an instance of {@link OrderMethods }
     * 
     */
    public OrderMethods createOrderMethods() {
        return new OrderMethods();
    }

    /**
     * Create an instance of {@link OrderMethod }
     * 
     */
    public OrderMethod createOrderMethod() {
        return new OrderMethod();
    }

    /**
     * Create an instance of {@link OrderTarget }
     * 
     */
    public OrderTarget createOrderTarget() {
        return new OrderTarget();
    }

    /**
     * Create an instance of {@link OtherOrderTarget }
     * 
     */
    public OtherOrderTarget createOtherOrderTarget() {
        return new OtherOrderTarget();
    }

    /**
     * Create an instance of {@link SpendDetail }
     * 
     */
    public SpendDetail createSpendDetail() {
        return new SpendDetail();
    }

    /**
     * Create an instance of {@link TravelDetail }
     * 
     */
    public TravelDetail createTravelDetail() {
        return new TravelDetail();
    }

    /**
     * Create an instance of {@link AirDetail }
     * 
     */
    public AirDetail createAirDetail() {
        return new AirDetail();
    }

    /**
     * Create an instance of {@link TripType }
     * 
     */
    public TripType createTripType() {
        return new TripType();
    }

    /**
     * Create an instance of {@link AirLeg }
     * 
     */
    public AirLeg createAirLeg() {
        return new AirLeg();
    }

    /**
     * Create an instance of {@link Vendor }
     * 
     */
    public Vendor createVendor() {
        return new Vendor();
    }

    /**
     * Create an instance of {@link AirLegOrigin }
     * 
     */
    public AirLegOrigin createAirLegOrigin() {
        return new AirLegOrigin();
    }

    /**
     * Create an instance of {@link Airport }
     * 
     */
    public Airport createAirport() {
        return new Airport();
    }

    /**
     * Create an instance of {@link AirLegDestination }
     * 
     */
    public AirLegDestination createAirLegDestination() {
        return new AirLegDestination();
    }

    /**
     * Create an instance of {@link BookingClassCode }
     * 
     */
    public BookingClassCode createBookingClassCode() {
        return new BookingClassCode();
    }

    /**
     * Create an instance of {@link Rate }
     * 
     */
    public Rate createRate() {
        return new Rate();
    }

    /**
     * Create an instance of {@link UnitRate }
     * 
     */
    public UnitRate createUnitRate() {
        return new UnitRate();
    }

    /**
     * Create an instance of {@link TermReference }
     * 
     */
    public TermReference createTermReference() {
        return new TermReference();
    }

    /**
     * Create an instance of {@link Meal }
     * 
     */
    public Meal createMeal() {
        return new Meal();
    }

    /**
     * Create an instance of {@link AvailablePrice }
     * 
     */
    public AvailablePrice createAvailablePrice() {
        return new AvailablePrice();
    }

    /**
     * Create an instance of {@link Penalty }
     * 
     */
    public Penalty createPenalty() {
        return new Penalty();
    }

    /**
     * Create an instance of {@link CarRentalDetail }
     * 
     */
    public CarRentalDetail createCarRentalDetail() {
        return new CarRentalDetail();
    }

    /**
     * Create an instance of {@link CarRentalPickup }
     * 
     */
    public CarRentalPickup createCarRentalPickup() {
        return new CarRentalPickup();
    }

    /**
     * Create an instance of {@link CarRentalDropoff }
     * 
     */
    public CarRentalDropoff createCarRentalDropoff() {
        return new CarRentalDropoff();
    }

    /**
     * Create an instance of {@link CarRentalFee }
     * 
     */
    public CarRentalFee createCarRentalFee() {
        return new CarRentalFee();
    }

    /**
     * Create an instance of {@link LimitedMileage }
     * 
     */
    public LimitedMileage createLimitedMileage() {
        return new LimitedMileage();
    }

    /**
     * Create an instance of {@link HotelDetail }
     * 
     */
    public HotelDetail createHotelDetail() {
        return new HotelDetail();
    }

    /**
     * Create an instance of {@link RoomType }
     * 
     */
    public RoomType createRoomType() {
        return new RoomType();
    }

    /**
     * Create an instance of {@link Amenities }
     * 
     */
    public Amenities createAmenities() {
        return new Amenities();
    }

    /**
     * Create an instance of {@link RailDetail }
     * 
     */
    public RailDetail createRailDetail() {
        return new RailDetail();
    }

    /**
     * Create an instance of {@link RailLeg }
     * 
     */
    public RailLeg createRailLeg() {
        return new RailLeg();
    }

    /**
     * Create an instance of {@link RailLegOrigin }
     * 
     */
    public RailLegOrigin createRailLegOrigin() {
        return new RailLegOrigin();
    }

    /**
     * Create an instance of {@link RailLegDestination }
     * 
     */
    public RailLegDestination createRailLegDestination() {
        return new RailLegDestination();
    }

    /**
     * Create an instance of {@link PolicyViolation }
     * 
     */
    public PolicyViolation createPolicyViolation() {
        return new PolicyViolation();
    }

    /**
     * Create an instance of {@link PolicyViolationJustification }
     * 
     */
    public PolicyViolationJustification createPolicyViolationJustification() {
        return new PolicyViolationJustification();
    }

    /**
     * Create an instance of {@link TermsAndConditions }
     * 
     */
    public TermsAndConditions createTermsAndConditions() {
        return new TermsAndConditions();
    }

    /**
     * Create an instance of {@link FeeDetail }
     * 
     */
    public FeeDetail createFeeDetail() {
        return new FeeDetail();
    }

    /**
     * Create an instance of {@link LaborDetail }
     * 
     */
    public LaborDetail createLaborDetail() {
        return new LaborDetail();
    }

    /**
     * Create an instance of {@link Contractor }
     * 
     */
    public Contractor createContractor() {
        return new Contractor();
    }

    /**
     * Create an instance of {@link ContractorIdentifier }
     * 
     */
    public ContractorIdentifier createContractorIdentifier() {
        return new ContractorIdentifier();
    }

    /**
     * Create an instance of {@link JobDescription }
     * 
     */
    public JobDescription createJobDescription() {
        return new JobDescription();
    }

    /**
     * Create an instance of {@link Supervisor }
     * 
     */
    public Supervisor createSupervisor() {
        return new Supervisor();
    }

    /**
     * Create an instance of {@link WorkLocation }
     * 
     */
    public WorkLocation createWorkLocation() {
        return new WorkLocation();
    }

    /**
     * Create an instance of {@link ScheduleLine }
     * 
     */
    public ScheduleLine createScheduleLine() {
        return new ScheduleLine();
    }

    /**
     * Create an instance of {@link ScheduleLineReleaseInfo }
     * 
     */
    public ScheduleLineReleaseInfo createScheduleLineReleaseInfo() {
        return new ScheduleLineReleaseInfo();
    }

    /**
     * Create an instance of {@link SubcontractingComponent }
     * 
     */
    public SubcontractingComponent createSubcontractingComponent() {
        return new SubcontractingComponent();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Batch }
     * 
     */
    public Batch createBatch() {
        return new Batch();
    }

    /**
     * Create an instance of {@link PropertyValuation }
     * 
     */
    public PropertyValuation createPropertyValuation() {
        return new PropertyValuation();
    }

    /**
     * Create an instance of {@link PropertyReference }
     * 
     */
    public PropertyReference createPropertyReference() {
        return new PropertyReference();
    }

    /**
     * Create an instance of {@link ValueGroup }
     * 
     */
    public ValueGroup createValueGroup() {
        return new ValueGroup();
    }

    /**
     * Create an instance of {@link PropertyValue }
     * 
     */
    public PropertyValue createPropertyValue() {
        return new PropertyValue();
    }

    /**
     * Create an instance of {@link MasterAgreementReference }
     * 
     */
    public MasterAgreementReference createMasterAgreementReference() {
        return new MasterAgreementReference();
    }

    /**
     * Create an instance of {@link MasterAgreementIDInfo }
     * 
     */
    public MasterAgreementIDInfo createMasterAgreementIDInfo() {
        return new MasterAgreementIDInfo();
    }

    /**
     * Create an instance of {@link ItemOutIndustry }
     * 
     */
    public ItemOutIndustry createItemOutIndustry() {
        return new ItemOutIndustry();
    }

    /**
     * Create an instance of {@link ItemOutRetail }
     * 
     */
    public ItemOutRetail createItemOutRetail() {
        return new ItemOutRetail();
    }

    /**
     * Create an instance of {@link SerialNumberInfo }
     * 
     */
    public SerialNumberInfo createSerialNumberInfo() {
        return new SerialNumberInfo();
    }

    /**
     * Create an instance of {@link BatchInfo }
     * 
     */
    public BatchInfo createBatchInfo() {
        return new BatchInfo();
    }

    /**
     * Create an instance of {@link Packaging }
     * 
     */
    public Packaging createPackaging() {
        return new Packaging();
    }

    /**
     * Create an instance of {@link PackagingCode }
     * 
     */
    public PackagingCode createPackagingCode() {
        return new PackagingCode();
    }

    /**
     * Create an instance of {@link PackageID }
     * 
     */
    public PackageID createPackageID() {
        return new PackageID();
    }

    /**
     * Create an instance of {@link OrderedQuantity }
     * 
     */
    public OrderedQuantity createOrderedQuantity() {
        return new OrderedQuantity();
    }

    /**
     * Create an instance of {@link DispatchQuantity }
     * 
     */
    public DispatchQuantity createDispatchQuantity() {
        return new DispatchQuantity();
    }

    /**
     * Create an instance of {@link FreeGoodsQuantity }
     * 
     */
    public FreeGoodsQuantity createFreeGoodsQuantity() {
        return new FreeGoodsQuantity();
    }

    /**
     * Create an instance of {@link BestBeforeDate }
     * 
     */
    public BestBeforeDate createBestBeforeDate() {
        return new BestBeforeDate();
    }

    /**
     * Create an instance of {@link ReleaseInfo }
     * 
     */
    public ReleaseInfo createReleaseInfo() {
        return new ReleaseInfo();
    }

    /**
     * Create an instance of {@link ShipNoticeReleaseInfo }
     * 
     */
    public ShipNoticeReleaseInfo createShipNoticeReleaseInfo() {
        return new ShipNoticeReleaseInfo();
    }

    /**
     * Create an instance of {@link ShipNoticeReference }
     * 
     */
    public ShipNoticeReference createShipNoticeReference() {
        return new ShipNoticeReference();
    }

    /**
     * Create an instance of {@link ShipNoticeIDInfo }
     * 
     */
    public ShipNoticeIDInfo createShipNoticeIDInfo() {
        return new ShipNoticeIDInfo();
    }

    /**
     * Create an instance of {@link Correspondent }
     * 
     */
    public Correspondent createCorrespondent() {
        return new Correspondent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Identity")
    public JAXBElement<String> createIdentity(String value) {
        return new JAXBElement<String>(_Identity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SharedSecret")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSharedSecret(String value) {
        return new JAXBElement<String>(_SharedSecret_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "UserAgent")
    public JAXBElement<String> createUserAgent(String value) {
        return new JAXBElement<String>(_UserAgent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ShortName")
    public JAXBElement<String> createShortName(String value) {
        return new JAXBElement<String>(_ShortName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "TaxRegime")
    public JAXBElement<String> createTaxRegime(String value) {
        return new JAXBElement<String>(_TaxRegime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "DeliverTo")
    public JAXBElement<String> createDeliverTo(String value) {
        return new JAXBElement<String>(_DeliverTo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Street")
    public JAXBElement<String> createStreet(String value) {
        return new JAXBElement<String>(_Street_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "City")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "State")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PostalCode")
    public JAXBElement<BigInteger> createPostalCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_PostalCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "AreaOrCityCode")
    public JAXBElement<String> createAreaOrCityCode(String value) {
        return new JAXBElement<String>(_AreaOrCityCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Number")
    public JAXBElement<String> createNumber(String value) {
        return new JAXBElement<String>(_Number_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Extension")
    public JAXBElement<String> createExtension(String value) {
        return new JAXBElement<String>(_Extension_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ShippingContractNumber")
    public JAXBElement<String> createShippingContractNumber(String value) {
        return new JAXBElement<String>(_ShippingContractNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SupplierPartID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSupplierPartID(String value) {
        return new JAXBElement<String>(_SupplierPartID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SupplierPartAuxiliaryID")
    public JAXBElement<String> createSupplierPartAuxiliaryID(String value) {
        return new JAXBElement<String>(_SupplierPartAuxiliaryID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BuyerPartID")
    public JAXBElement<String> createBuyerPartID(String value) {
        return new JAXBElement<String>(_BuyerPartID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "UnitOfMeasure")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUnitOfMeasure(String value) {
        return new JAXBElement<String>(_UnitOfMeasure_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ManufacturerPartID")
    public JAXBElement<String> createManufacturerPartID(String value) {
        return new JAXBElement<String>(_ManufacturerPartID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "LeadTime")
    public JAXBElement<String> createLeadTime(String value) {
        return new JAXBElement<String>(_LeadTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "EANID")
    public JAXBElement<String> createEANID(String value) {
        return new JAXBElement<String>(_EANID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "EuropeanWasteCatalogID")
    public JAXBElement<String> createEuropeanWasteCatalogID(String value) {
        return new JAXBElement<String>(_EuropeanWasteCatalogID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PlannedAcceptanceDays")
    public JAXBElement<String> createPlannedAcceptanceDays(String value) {
        return new JAXBElement<String>(_PlannedAcceptanceDays_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "MaxQuantity")
    public JAXBElement<String> createMaxQuantity(String value) {
        return new JAXBElement<String>(_MaxQuantity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "MinQuantity")
    public JAXBElement<String> createMinQuantity(String value) {
        return new JAXBElement<String>(_MinQuantity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "OrderProtocol")
    public JAXBElement<String> createOrderProtocol(String value) {
        return new JAXBElement<String>(_OrderProtocol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ComponentID")
    public JAXBElement<String> createComponentID(String value) {
        return new JAXBElement<String>(_ComponentID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ProductRevisionID")
    public JAXBElement<String> createProductRevisionID(String value) {
        return new JAXBElement<String>(_ProductRevisionID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BuyerBatchID")
    public JAXBElement<String> createBuyerBatchID(String value) {
        return new JAXBElement<String>(_BuyerBatchID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SupplierBatchID")
    public JAXBElement<String> createSupplierBatchID(String value) {
        return new JAXBElement<String>(_SupplierBatchID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ParentID")
    public JAXBElement<String> createParentID(String value) {
        return new JAXBElement<String>(_ParentID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PromotionVariantID")
    public JAXBElement<String> createPromotionVariantID(String value) {
        return new JAXBElement<String>(_PromotionVariantID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PromotionDealID")
    public JAXBElement<String> createPromotionDealID(String value) {
        return new JAXBElement<String>(_PromotionDealID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SerialNumber")
    public JAXBElement<String> createSerialNumber(String value) {
        return new JAXBElement<String>(_SerialNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PackagingLevelCode")
    public JAXBElement<String> createPackagingLevelCode(String value) {
        return new JAXBElement<String>(_PackagingLevelCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PackageTypeCodeIdentifierCode")
    public JAXBElement<String> createPackageTypeCodeIdentifierCode(String value) {
        return new JAXBElement<String>(_PackageTypeCodeIdentifierCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ShippingContainerSerialCode")
    public JAXBElement<String> createShippingContainerSerialCode(String value) {
        return new JAXBElement<String>(_ShippingContainerSerialCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ShippingContainerSerialCodeReference")
    public JAXBElement<String> createShippingContainerSerialCodeReference(String value) {
        return new JAXBElement<String>(_ShippingContainerSerialCodeReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "GlobalIndividualAssetID")
    public JAXBElement<String> createGlobalIndividualAssetID(String value) {
        return new JAXBElement<String>(_GlobalIndividualAssetID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ReturnablePackageID")
    public JAXBElement<String> createReturnablePackageID(String value) {
        return new JAXBElement<String>(_ReturnablePackageID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PackageTrackingID")
    public JAXBElement<String> createPackageTrackingID(String value) {
        return new JAXBElement<String>(_PackageTrackingID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ShippingMark")
    public JAXBElement<String> createShippingMark(String value) {
        return new JAXBElement<String>(_ShippingMark_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "QuantityVarianceNote")
    public JAXBElement<String> createQuantityVarianceNote(String value) {
        return new JAXBElement<String>(_QuantityVarianceNote_QNAME, String.class, null, value);
    }

}
