//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.15 at 12:54:41 PM MST 
//


package com.orderwire.cxml.dll;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}GlobalIndividualAssetID" minOccurs="0"/&gt;
 *         &lt;element ref="{}ReturnablePackageID" minOccurs="0"/&gt;
 *         &lt;element ref="{}PackageTrackingID" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalIndividualAssetID",
    "returnablePackageID",
    "packageTrackingID"
})
@XmlRootElement(name = "PackageID")
public class PackageID {

    @XmlElement(name = "GlobalIndividualAssetID")
    protected String globalIndividualAssetID;
    @XmlElement(name = "ReturnablePackageID")
    protected String returnablePackageID;
    @XmlElement(name = "PackageTrackingID")
    protected String packageTrackingID;

    /**
     * Gets the value of the globalIndividualAssetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalIndividualAssetID() {
        return globalIndividualAssetID;
    }

    /**
     * Sets the value of the globalIndividualAssetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalIndividualAssetID(String value) {
        this.globalIndividualAssetID = value;
    }

    /**
     * Gets the value of the returnablePackageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnablePackageID() {
        return returnablePackageID;
    }

    /**
     * Sets the value of the returnablePackageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnablePackageID(String value) {
        this.returnablePackageID = value;
    }

    /**
     * Gets the value of the packageTrackingID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageTrackingID() {
        return packageTrackingID;
    }

    /**
     * Sets the value of the packageTrackingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageTrackingID(String value) {
        this.packageTrackingID = value;
    }

}
