//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.15 at 12:54:41 PM MST 
//


package com.orderwire.cxml.dll;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{}PackagingCode" maxOccurs="unbounded"/&gt;
 *             &lt;element ref="{}Dimension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element ref="{}Dimension" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}Description" minOccurs="0"/&gt;
 *         &lt;element ref="{}PackagingLevelCode" minOccurs="0"/&gt;
 *         &lt;element ref="{}PackageTypeCodeIdentifierCode" minOccurs="0"/&gt;
 *         &lt;element ref="{}ShippingContainerSerialCode" minOccurs="0"/&gt;
 *         &lt;element ref="{}ShippingContainerSerialCodeReference" minOccurs="0"/&gt;
 *         &lt;element ref="{}PackageID" minOccurs="0"/&gt;
 *         &lt;element ref="{}ShippingMark" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}OrderedQuantity" minOccurs="0"/&gt;
 *         &lt;element ref="{}DispatchQuantity" minOccurs="0"/&gt;
 *         &lt;element ref="{}FreeGoodsQuantity" minOccurs="0"/&gt;
 *         &lt;element ref="{}QuantityVarianceNote" minOccurs="0"/&gt;
 *         &lt;element ref="{}BestBeforeDate" minOccurs="0"/&gt;
 *         &lt;element ref="{}Extrinsic" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Packaging")
public class Packaging {

    @XmlElementRefs({
        @XmlElementRef(name = "PackagingCode", type = PackagingCode.class, required = false),
        @XmlElementRef(name = "Dimension", type = Dimension.class, required = false),
        @XmlElementRef(name = "Description", type = Description.class, required = false),
        @XmlElementRef(name = "PackagingLevelCode", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PackageTypeCodeIdentifierCode", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ShippingContainerSerialCode", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ShippingContainerSerialCodeReference", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PackageID", type = PackageID.class, required = false),
        @XmlElementRef(name = "ShippingMark", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OrderedQuantity", type = OrderedQuantity.class, required = false),
        @XmlElementRef(name = "DispatchQuantity", type = DispatchQuantity.class, required = false),
        @XmlElementRef(name = "FreeGoodsQuantity", type = FreeGoodsQuantity.class, required = false),
        @XmlElementRef(name = "QuantityVarianceNote", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BestBeforeDate", type = BestBeforeDate.class, required = false),
        @XmlElementRef(name = "Extrinsic", type = Extrinsic.class, required = false)
    })
    protected List<Object> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Dimension" is used by two different parts of a schema. See: 
     * line 1682 of file:/C:/Users/inter/Documents/NetBeansProjects/jaxbdll/src/main/xsd/Purchase-Order-with-Annotations-DLL.xsd
     * line 1680 of file:/C:/Users/inter/Documents/NetBeansProjects/jaxbdll/src/main/xsd/Purchase-Order-with-Annotations-DLL.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackagingCode }
     * {@link Dimension }
     * {@link Description }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link PackageID }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link OrderedQuantity }
     * {@link DispatchQuantity }
     * {@link FreeGoodsQuantity }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link BestBeforeDate }
     * {@link Extrinsic }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
