//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.15 at 12:54:41 PM MST 
//


package com.orderwire.cxml.dll;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ExemptReason" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="exemptCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exemptReason"
})
@XmlRootElement(name = "TaxExemption")
public class TaxExemption {

    @XmlElement(name = "ExemptReason")
    protected ExemptReason exemptReason;
    @XmlAttribute(name = "exemptCode", required = true)
    protected String exemptCode;

    /**
     * Gets the value of the exemptReason property.
     * 
     * @return
     *     possible object is
     *     {@link ExemptReason }
     *     
     */
    public ExemptReason getExemptReason() {
        return exemptReason;
    }

    /**
     * Sets the value of the exemptReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExemptReason }
     *     
     */
    public void setExemptReason(ExemptReason value) {
        this.exemptReason = value;
    }

    /**
     * Gets the value of the exemptCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExemptCode() {
        return exemptCode;
    }

    /**
     * Sets the value of the exemptCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExemptCode(String value) {
        this.exemptCode = value;
    }

}
