//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.15 at 12:54:41 PM MST 
//


package com.orderwire.cxml.dll;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}QuantityTolerance" minOccurs="0"/&gt;
 *         &lt;element ref="{}PriceTolerance" minOccurs="0"/&gt;
 *         &lt;element ref="{}TimeTolerance" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quantityTolerance",
    "priceTolerance",
    "timeTolerance"
})
@XmlRootElement(name = "Tolerances")
public class Tolerances {

    @XmlElement(name = "QuantityTolerance")
    protected QuantityTolerance quantityTolerance;
    @XmlElement(name = "PriceTolerance")
    protected PriceTolerance priceTolerance;
    @XmlElement(name = "TimeTolerance")
    protected TimeTolerance timeTolerance;

    /**
     * Gets the value of the quantityTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityTolerance }
     *     
     */
    public QuantityTolerance getQuantityTolerance() {
        return quantityTolerance;
    }

    /**
     * Sets the value of the quantityTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityTolerance }
     *     
     */
    public void setQuantityTolerance(QuantityTolerance value) {
        this.quantityTolerance = value;
    }

    /**
     * Gets the value of the priceTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link PriceTolerance }
     *     
     */
    public PriceTolerance getPriceTolerance() {
        return priceTolerance;
    }

    /**
     * Sets the value of the priceTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceTolerance }
     *     
     */
    public void setPriceTolerance(PriceTolerance value) {
        this.priceTolerance = value;
    }

    /**
     * Gets the value of the timeTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link TimeTolerance }
     *     
     */
    public TimeTolerance getTimeTolerance() {
        return timeTolerance;
    }

    /**
     * Sets the value of the timeTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeTolerance }
     *     
     */
    public void setTimeTolerance(TimeTolerance value) {
        this.timeTolerance = value;
    }

}
